# Generated by Django 4.1.6 on 2023-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Serial', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Serial', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Serial', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Serial', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=2555)),
                ('Number', models.IntegerField(max_length=255)),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Serial', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
