# Generated by Django 4.1.6 on 2023-02-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurements',
            name='Date',
            field=models.CharField(max_length=255),
        ),
    ]
