# Generated by Django 4.1.6 on 2023-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_donors_issuing_purchases_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='Items_supplied',
            field=models.TextField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='Items_supplied',
            field=models.TextField(max_length=2555),
        ),
    ]
